name: fortfolio
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  intl_phone_field: ^3.1.0
  fpdart: ^0.2.0
  google_fonts: ^3.0.1
  carousel_slider: ^4.1.1
  cached_network_image: ^3.2.2
  flutter_svg: ^1.1.5
  timelines: ^0.1.0
  url_launcher: ^6.1.6
  json_annotation: ^4.7.0
  freezed_annotation: ^2.1.0
  firebase_core: ^1.23.0
  firebase_auth: ^3.10.0
  cloud_firestore: ^3.4.9
  firebase_storage: ^10.3.9
  connectivity_plus: ^2.3.7
  equatable: ^2.0.5
  dartz: ^0.10.1
  injectable: ^1.5.3
  auto_route: ^5.0.1
  salomon_bottom_bar: ^3.3.1
  webview_flutter: ^3.0.4
  local_auth: ^2.1.2
  screenshot: ^1.2.3
  share_plus: ^4.4.0
  image_picker: ^0.8.5+3
  nanoid: ^1.0.0
  path_provider: ^2.0.11
  uuid: ^3.0.6
  cloud_functions: ^3.3.8
  jiffy: ^5.0.0
  flutter_launcher_icons: ^0.10.0
  package_info_plus: ^1.4.3+1
  firebase_app_check: ^0.0.7+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.1
  freezed: ^2.1.0+1
  json_serializable: ^6.4.1
  injectable_generator: ^1.5.4
  intl: ^0.17.0

flutter_icons:
  android: true
  ios: false
  image_path: "images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - images/
        
    
    
                                      