name: fortfolio
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.17
  intl_phone_field: ^3.1.0
  fpdart: ^0.4.0
  google_fonts: ^4.0.3
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.0+1
  timelines: ^0.1.0
  url_launcher: ^6.1.8
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  connectivity_plus: ^3.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  injectable: ^2.1.0
  auto_route: ^5.0.4
  salomon_bottom_bar: ^3.3.1
  webview_flutter: ^4.0.2
  local_auth: ^2.1.3
  screenshot: ^1.3.0
  share_plus: ^6.3.0
  image_picker: ^0.8.6+1
  nanoid: ^1.0.0
  uuid: ^3.0.7
  cloud_functions: ^4.0.7
  jiffy: ^5.0.0
  flutter_launcher_icons: ^0.11.0
  package_info_plus: ^3.0.2
  firebase_app_check: ^0.1.1+8
  pattern_formatter: ^2.0.0
  elegant_notification: ^1.6.4
  path_provider: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  injectable_generator: ^2.1.3
  intl: ^0.17.0


flutter_icons:
  android: true
  ios: false
  image_path: "images/launch_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "images/launch_logo.png"

flutter:
  uses-material-design: true
  assets:
    - images/
        
    
    
                                      