name: fortfolio
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  otp_text_field: ^1.1.1
  intl_phone_field: ^3.0.0
  nanoid: ^1.0.0
  google_fonts: ^2.1.1
  carousel_slider: ^4.0.0
  cached_network_image: ^3.2.0
  flutter_svg: ^1.0.0
  timelines: ^0.1.0
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.6
  firebase_storage: ^10.2.5
  connectivity_plus: ^2.2.0
  equatable: ^2.0.3
  dartz: ^0.10.1
  injectable: ^1.5.3
  get_it: ^7.2.0
  auto_route: ^3.2.2
  salomon_bottom_bar: ^3.2.0
  progress_indicators: ^1.0.0
  kt_dart: ^0.10.0
  rxdart: ^0.27.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  auto_route_generator: ^3.2.1
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  injectable_generator: ^1.5.3

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
